import type { Theme } from '../shared/types.js';

const ID='prismdesk-background';
const STYLE='prismdesk-style';
export function buildApplyScript(theme:Theme, imageData?:string):string {
  const config=JSON.stringify({...theme,imageData:imageData??null});
  return `(()=>{const c=${config};window.__prismdeskCleanup?.();document.getElementById('${ID}')?.remove();document.getElementById('${STYLE}')?.remove();const s=document.createElement('style');s.id='${STYLE}';s.textContent='html,body,#root{background:transparent!important} #${ID}{position:fixed;inset:-40px;z-index:0;pointer-events:none;overflow:hidden;filter:brightness('+c.brightness+') blur('+c.blur+'px);opacity:'+c.opacity+'} #${ID} canvas,#${ID} .pd-img{width:100%;height:100%;object-fit:cover} #root{position:relative;z-index:1} .teams-container,.teams-container.is-mac,[data-view-id],.conversation-list,.main-content,.main-content--welcome,.sidebar-next,.wb-home-route,[class*=_gridViewItem_],[class*=_MainContentSurface_]{background:transparent!important} [data-view-id=sidebar],[data-view-id=detail-panel]{background:color-mix(in srgb,var(--cb-bg-primary,#111827) 78%,transparent)!important;backdrop-filter:blur(18px)} [data-view-id=main-content]{background:linear-gradient(180deg,transparent 0 44%,color-mix(in srgb,var(--cb-bg-primary,#111827) 70%,transparent) 100%)!important}';document.head.appendChild(s);const host=document.createElement('div');host.id='${ID}';host.dataset.prismdesk='1';document.body.prepend(host);let raf=0,last=0,ctx,canvas,resize;if(c.kind==='image'){const img=document.createElement('img');img.className='pd-img';img.src=c.imageData;host.appendChild(img)}else{canvas=document.createElement('canvas');host.appendChild(canvas);ctx=canvas.getContext('2d');resize=()=>{canvas.width=Math.ceil(innerWidth/devicePixelRatio);canvas.height=Math.ceil(innerHeight/devicePixelRatio)};resize();addEventListener('resize',resize);const draw=t=>{if(!c.motion||document.hidden)return;const wait=1000/c.fps;if(t-last>=wait){last=t;const w=canvas.width,h=canvas.height,g=ctx.createLinearGradient(0,0,w,h);const p=t*.00008*c.speed;g.addColorStop(0,'hsl('+((p*120+220)%360)+' 78% 18%)');g.addColorStop(.48,'hsl('+((p*180+280)%360)+' 76% 34%)');g.addColorStop(1,'hsl('+((p*90+165)%360)+' 70% 20%)');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);for(let i=0;i<3;i++){const x=w*(.2+i*.3+Math.sin(p*10+i)*.08),y=h*(.45+Math.cos(p*8+i)*.18),r=Math.max(w,h)*.42,rg=ctx.createRadialGradient(x,y,0,x,y,r);rg.addColorStop(0,['#22d3ee99','#a855f799','#10b98188'][i]);rg.addColorStop(1,'transparent');ctx.fillStyle=rg;ctx.fillRect(0,0,w,h)}}raf=requestAnimationFrame(draw)};if(c.motion)raf=requestAnimationFrame(draw);else{c.motion=true;draw(0);c.motion=false}}const visibility=()=>{if(!canvas)return;if(document.hidden){cancelAnimationFrame(raf);raf=0}else if(c.motion&&!raf)raf=requestAnimationFrame(draw)};document.addEventListener('visibilitychange',visibility);window.__prismdeskCleanup=()=>{cancelAnimationFrame(raf);if(resize)removeEventListener('resize',resize);document.removeEventListener('visibilitychange',visibility);host.remove();s.remove();delete window.__prismdeskCleanup};document.documentElement.dataset.prismdesk='applied';return {ok:true,id:'${ID}',kind:c.kind}})()`;
}
export const removeScript=`(()=>{window.__prismdeskCleanup?.();document.getElementById('${ID}')?.remove();document.getElementById('${STYLE}')?.remove();delete document.documentElement.dataset.prismdesk;return !document.getElementById('${ID}')})()`;
export const statusScript=`(()=>({applied:Boolean(document.getElementById('${ID}')),count:document.querySelectorAll('#${ID}').length,structure:Boolean(document.documentElement&&document.body)}))()`;


