import type { Theme } from '../shared/types.js';

const ID='prismdesk-background';
const STYLE='prismdesk-style';
// Only selectors that were observed on real client nodes are neutralised. A generic
// attribute rule such as [data-view-id] also matches unrelated WorkBuddy home-grid
// cards, so it must never be used to style a client surface.
const baseCss='html,body,#root{background:transparent!important} .teams-container,.teams-container.is-mac,.conversation-list,.main-content,.main-content--welcome,.sidebar-next,.wb-home-route,[class*=_gridViewItem_],[class*=_MainContentSurface_]{background:transparent!important}';
const layerCss=`#${ID}{position:fixed;inset:-40px;z-index:-1;pointer-events:none;overflow:hidden;filter:brightness('+c.brightness+') blur('+c.blur+'px);opacity:'+c.opacity+'} #${ID} canvas,#${ID} .pd-img{display:block;width:100%;height:100%;object-fit:cover}`;
export function buildApplyScript(theme:Theme, imageData?:string):string {
  const config=JSON.stringify({...theme,imageData:imageData??null});
  return `(()=>{const c=${config};window.__prismdeskCleanup?.();document.querySelectorAll('#${ID}').forEach(n=>n.remove());document.querySelectorAll('#${STYLE}').forEach(n=>n.remove());const s=document.createElement('style');s.id='${STYLE}';s.textContent='${baseCss} ${layerCss}';document.head.appendChild(s);const host=document.createElement('div');host.id='${ID}';host.dataset.prismdesk='1';document.body.prepend(host);let raf=0,last=0,ctx,canvas,resize,paint,tick;if(c.kind==='image'){const img=document.createElement('img');img.className='pd-img';img.alt='';img.src=c.imageData;host.appendChild(img)}else{canvas=document.createElement('canvas');canvas.setAttribute('aria-hidden','true');host.appendChild(canvas);ctx=canvas.getContext('2d');paint=t=>{const w=canvas.width,h=canvas.height,e=t||0,g=ctx.createLinearGradient(0,0,w,h),p=e*.00008*c.speed;g.addColorStop(0,'hsl('+((p*120+220)%360)+' 78% 18%)');g.addColorStop(.48,'hsl('+((p*180+280)%360)+' 76% 34%)');g.addColorStop(1,'hsl('+((p*90+165)%360)+' 70% 20%)');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);for(let i=0;i<3;i++){const x=w*(.2+i*.3+Math.sin(p*10+i)*.08),y=h*(.45+Math.cos(p*8+i)*.18),r=Math.max(w,h)*.42,rg=ctx.createRadialGradient(x,y,0,x,y,r);rg.addColorStop(0,['#22d3ee99','#a855f799','#10b98188'][i]);rg.addColorStop(1,'transparent');ctx.fillStyle=rg;ctx.fillRect(0,0,w,h)}};resize=()=>{const k=Math.min(4,Math.max(1,window.devicePixelRatio||1));canvas.width=Math.max(1,Math.round(innerWidth*k));canvas.height=Math.max(1,Math.round(innerHeight*k));paint(last)};resize();addEventListener('resize',resize);tick=t=>{if(document.hidden){raf=0;return}if(t-last>=1000/c.fps){last=t;paint(t)}raf=requestAnimationFrame(tick)};if(c.motion)raf=requestAnimationFrame(tick)}const visibility=()=>{if(!canvas)return;if(document.hidden){cancelAnimationFrame(raf);raf=0}else if(c.motion&&!raf){paint(last);raf=requestAnimationFrame(tick)}};document.addEventListener('visibilitychange',visibility);window.__prismdeskCleanup=()=>{cancelAnimationFrame(raf);if(resize)removeEventListener('resize',resize);document.removeEventListener('visibilitychange',visibility);host.remove();s.remove();delete window.__prismdeskCleanup};document.documentElement.dataset.prismdesk='applied';return {ok:true,id:'${ID}',kind:c.kind,painted:c.kind==='image'||Boolean(canvas&&canvas.width>0)}})()`;
}
export const removeScript=`(()=>{window.__prismdeskCleanup?.();document.querySelectorAll('#${ID}').forEach(n=>n.remove());document.querySelectorAll('#${STYLE}').forEach(n=>n.remove());delete document.documentElement.dataset.prismdesk;return !document.getElementById('${ID}')})()`;
export const statusScript=`(()=>{const h=document.getElementById('${ID}'),cv=h?.querySelector('canvas');let painted=null;if(cv){try{painted=cv.getContext('2d').getImageData(Math.floor(cv.width/2),Math.floor(cv.height/2),1,1).data[3]>0}catch(error){painted=null}}return {applied:Boolean(h),count:document.querySelectorAll('#${ID}').length,painted,structure:Boolean(document.documentElement&&document.body)}})()`;
