declare global { interface Window { prism:any } }
let theme:any; const $=(id:string)=>document.getElementById(id)!;
const fields=['brightness','opacity','blur','speed'] as const;
function read(){for(const k of fields)theme[k]=Number(($(`${k}`) as HTMLInputElement).value);theme.motion=($('motion') as HTMLInputElement).checked;theme.fps=Number(($('fps') as HTMLSelectElement).value);return theme}
function render(){for(const k of fields){const el=$(`${k}`) as HTMLInputElement;el.value=String(theme[k]);$(`${k}Out`).textContent=k==='blur'?`${theme[k]}px`:`${Math.round(theme[k]*100)}%`}($('motion') as HTMLInputElement).checked=theme.motion;($('fps') as HTMLSelectElement).value=String(theme.fps);$('themeName').textContent=theme.name;const p=$('preview');p.classList.toggle('image',theme.kind==='image');p.style.filter=`brightness(${theme.brightness}) blur(${theme.blur/8}px)`;p.style.opacity=String(theme.opacity);p.style.animationDuration=`${8/theme.speed}s`;p.style.animationPlayState=theme.motion?'running':'paused';if(theme.kind==='image'&&theme.imagePath)p.style.backgroundImage=`url(file:///${theme.imagePath.replaceAll('\\','/')})`;document.querySelectorAll('[data-kind]').forEach(x=>x.classList.toggle('active',(x as HTMLElement).dataset.kind===theme.kind))}
function notify(s:string,error=false){$('notice').textContent=s;$('notice').style.color=error?'#fca5a5':'#8ee0c2'}
async function statuses(){const list=await window.prism.statuses();$('targets').innerHTML=list.map((s:any)=>`<article class="card"><div class="card-head"><div><h3>${s.name}</h3><div class="meta">${s.version||'—'} · ${s.installPath||s.detail}</div></div><span class="pill ${s.status}">${s.detail}</span></div><div class="actions"><button data-connect="${s.id}" ${!s.installed||s.connected?'disabled':''}>连接</button><button data-apply="${s.id}" ${!s.connected?'disabled':''}>应用</button><button data-restore="${s.id}" ${!s.connected?'disabled':''}>恢复默认</button></div></article>`).join('');document.querySelectorAll('[data-connect]').forEach(b=>(b as HTMLButtonElement).onclick=()=>act(()=>window.prism.launch((b as HTMLElement).dataset.connect),'已连接'));document.querySelectorAll('[data-apply]').forEach(b=>(b as HTMLButtonElement).onclick=()=>act(()=>window.prism.apply((b as HTMLElement).dataset.apply,read()),'背景已应用'));document.querySelectorAll('[data-restore]').forEach(b=>(b as HTMLButtonElement).onclick=()=>act(()=>window.prism.restore((b as HTMLElement).dataset.restore),'已恢复默认'))}
async function act(fn:()=>Promise<any>,ok:string){try{await fn();notify(ok);await statuses()}catch(e){notify((e as Error).message,true)}}
async function init(){theme=await window.prism.load();render();await statuses();for(const k of fields)$(`${k}`).addEventListener('input',()=>{read();render()});$('motion').onchange=$('fps').onchange=()=>{read();render()};document.querySelectorAll('[data-kind]').forEach(b=>(b as HTMLButtonElement).onclick=()=>{theme.kind=(b as HTMLElement).dataset.kind;render()});$('pick').onclick=async()=>{const p=await window.prism.image();if(p){theme.kind='image';theme.imagePath=p;render()}};$('importTheme').onclick=async()=>{const t=await window.prism.importTheme();if(t){theme=t;render();notify('主题已校验并导入')}};$('save').onclick=()=>act(()=>window.prism.save(read()),'设置已保存');$('refresh').onclick=statuses}
init().catch(e=>notify(e.message,true));
